@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>> {
Interface ReadOnlyInventory <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Class Inventory
Class RecipeBook
Class ReadOnlyInventory
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs


Package Ingredient <<Rectangle>> #F4F6F6 {
Class "Database <<Ingredient>>" as IngredientDatabase
Class "UniqueDataList <<Ingredient>> " as UniqueIngredientList
Class Ingredient
}

Package Recipe <<Rectangle>> #F4F6F6 {
Class "Database <<Recipe>>" as RecipeDatabase
Class "UniqueDataList <<Recipe>> " as UniqueRecipeList
Class Recipe
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

Inventory .up.|> ReadOnlyInventory

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyInventory
ModelManager -left-> "1" Inventory
ModelManager -right-> "1" RecipeBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

Inventory --|> IngredientDatabase
IngredientDatabase *--> "1" UniqueIngredientList
UniqueIngredientList --> "~* all" Ingredient


RecipeBook --|> RecipeDatabase
RecipeDatabase *--> "1" UniqueRecipeList
UniqueRecipeList --> "~* all" Recipe


ModelManager -->"~* filtered" Ingredient
ModelManager -->"~* filtered" Recipe

Recipe -down[hidden]-> Ingredient
@enduml
