@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>> {
Interface ReadOnlyInventory <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Class Inventory
Class RecipeBook
Class ReadOnlyInventory
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs


Package Ingredient <<Rectangle>> #F4F6F6 {
Class UniqueIngredientList
Class Ingredient
Class Description
Class ExpiryDate
Class Name
Class Quantity
Class Tag
}

Package Recipe <<Rectangle>> #F4F6F6 {
Class UniqueRecipeList
Class RecipeName
Class Recipe
Class BaseIngredient
Class Step
Class RecipeDescription
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

Inventory .up.|> ReadOnlyInventory

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyInventory
ModelManager -left-> "1" Inventory
ModelManager -right-> "1" RecipeBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

Inventory *--> "1" UniqueIngredientList
UniqueIngredientList --> "~* all" Ingredient
Ingredient *--> Name
Ingredient *--> Quantity
Ingredient *--> ExpiryDate
Ingredient *--> Description
Ingredient *--> "*" Tag


RecipeBook *--> "1" UniqueRecipeList
UniqueRecipeList --> "~* all" Recipe
Recipe *--> RecipeName
Recipe *--> "*" BaseIngredient
Recipe *--> "*" Step
Recipe *--> "0..1" RecipeDescription


Name -[hidden]right-> Quantity
Quantity -[hidden]right-> Description
Description -[hidden]right-> ExpiryDate

ModelManager -->"~* filtered" Ingredient
ModelManager -->"~* filtered" Recipe
@enduml
