@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

package "UserPrefs Storage" #F4F6F6{
Interface UserPrefsStorage <<Interface>>
Class JsonUserPrefsStorage
}

Interface Storage <<Interface>>
Class StorageManager

package "Inventory Storage" #F4F6F6{
Interface InventoryStorage <<Interface>>
Class JsonInventoryStorage
Class JsonSerializableInventory
Class JsonAdaptedPerson
Class JsonAdaptedTag
}

package "RecipeBook Storage" #F4F6F6{
Interface RecipeBookStorage <<Interface>>
Class JsonRecipeBookStorage
Class JsonSerializableRecipeBook
Class JsonAdaptedRecipe
Class JsonAdaptedIngredient
Class JsonAdaptedStep
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" InventoryStorage
StorageManager -up-> "1" RecipeBookStorage


Storage -left-|> UserPrefsStorage
Storage -right-|> InventoryStorage
Storage -down-|> RecipeBookStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage

' inventory stuff
JsonInventoryStorage .up.|> InventoryStorage
JsonInventoryStorage ..> JsonSerializableInventory
JsonSerializableInventory --> "*" JsonAdaptedPerson
JsonAdaptedPerson --> "*" JsonAdaptedTag

' recipebook stuff
JsonRecipeBookStorage .up.|> RecipeBookStorage
JsonRecipeBookStorage ..> JsonSerializableRecipeBook
JsonSerializableRecipeBook --> "*" JsonAdaptedRecipe
JsonAdaptedRecipe --> "*" JsonAdaptedIngredient
JsonAdaptedRecipe --> "*" JsonAdaptedStep

@enduml
