@startuml
!include <office/Concepts/globe_internet>
!include <office/Concepts/documents>
!include <office/Users/user>
!include style.puml

Class ModelManager MODEL_COLOR

Package UI <<Rectangle>> {
    Class MainWindow UI_COLOR
    Class Observer<<Interface>> UI_COLOR
    Class UiState UI_COLOR
}

MainWindow --|> Observer
UiState *--> "1" ModelManager
UiState *--> "1" Observer

@enduml
